name: Creator
main: com.rusketh.creator.CreatorPlugin
authors: [Rusketh, Oskar]
website: Rusketh.com
version: 0.3
description: Used to build and create.
softdepend: [ Vault ]
commands:
  creator:
    description: Used to build and create.
    usage: |
        /<command> <help>
    aliases: [cr]